services:
  - type: web
    name: COMP4651-stock-prediction-website
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11"